cmake_minimum_required(VERSION 3.10)
project(httpserver)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_BUILD_TYPE Debug)
set(EXECUTABLE_OUTPUT_PATH  ${CMAKE_SOURCE_DIR}/bin)

include_directories(./include)
# include_directories(./src/tcp)
aux_source_directory(./src/tcp src_tcp)
aux_source_directory(./src/http src_http)
# aux_source_directory(./src/rpc src_rpc)
# aux_source_directory(./src/rpc/services src_rpc_serices)
# aux_source_directory(./src/utils src_utils)

# add_executable(contexttest src/http/context.cpp src/http/contexttest.cpp)
add_executable(tasktest test/utils/tasktest.cpp)
add_executable(echoserver ${src_tcp} test/tcp/echoserver.cpp)
add_executable(tcpclient test/tcp/client.cpp)
add_executable(vpnserver ${src_tcp} test/tcp/vpn.cpp)

# add_executable(servertest ${src_tcp} src/test/servertest.cpp)
add_executable(httpclient ${src_tcp} ${src_http} test/http/clienttest.cpp)
add_executable(httpserver ${src_tcp} ${src_http} test/http/servertest.cpp)
# add_executable(test ${src_tcp} ${src_http} src/test/test.cpp)
# add_executable(logtest src/test/logtest.cpp src/tcp/log.cpp)
# add_executable(fileserver ./src/test/fileservertest.cpp ./src/examples/fileserver.cpp ${src_tcp} ${src_http})

# add_executable(rpcserver ${src_tcp} ${src_rpc} ${src_rpc_serices} ${src_util} ./src/rpc/test/server.cpp)
# add_executable(rpcclient ${src_tcp} ${src_rpc} ${src_util} ./src/rpc/test/client.cpp)
# add_executable(channeltest test/utils/channeltest.cpp)

# target_link_libraries(rpcserver protobuf)
# target_link_libraries(rpcclient protobuf)