// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

#include "rpc/common.pb.h"

#include <algorithm>

#include <google/protobuf/descriptor.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
#include <google/protobuf/wire_format_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace rpc
{
PROTOBUF_CONSTEXPR Request::Request(::_pbi::ConstantInitialized)
    : _impl_{/*decltype(_impl_.method_)*/ {&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}},
             /*decltype(_impl_.input_)*/ {&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}},
             /*decltype(_impl_._cached_size_)*/ {}}
{
}
struct RequestDefaultTypeInternal
{
    PROTOBUF_CONSTEXPR RequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
    ~RequestDefaultTypeInternal() {}
    union {
        Request _instance;
    };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RequestDefaultTypeInternal
    _Request_default_instance_;
PROTOBUF_CONSTEXPR Response::Response(::_pbi::ConstantInitialized)
    : _impl_{/*decltype(_impl_.method_)*/ {&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}},
             /*decltype(_impl_.output_)*/ {&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}},
             /*decltype(_impl_.iserror_)*/ false, /*decltype(_impl_._cached_size_)*/ {}}
{
}
struct ResponseDefaultTypeInternal
{
    PROTOBUF_CONSTEXPR ResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
    ~ResponseDefaultTypeInternal() {}
    union {
        Response _instance;
    };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ResponseDefaultTypeInternal
    _Response_default_instance_;
} // namespace rpc
static ::_pb::Metadata file_level_metadata_common_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_common_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_common_2eproto = nullptr;

const uint32_t TableStruct_common_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    ~0u, // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::rpc::Request, _internal_metadata_),
    ~0u, // no _extensions_
    ~0u, // no _oneof_case_
    ~0u, // no _weak_field_map_
    ~0u, // no _inlined_string_donated_
    PROTOBUF_FIELD_OFFSET(::rpc::Request, _impl_.method_),
    PROTOBUF_FIELD_OFFSET(::rpc::Request, _impl_.input_),
    ~0u, // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::rpc::Response, _internal_metadata_),
    ~0u, // no _extensions_
    ~0u, // no _oneof_case_
    ~0u, // no _weak_field_map_
    ~0u, // no _inlined_string_donated_
    PROTOBUF_FIELD_OFFSET(::rpc::Response, _impl_.method_),
    PROTOBUF_FIELD_OFFSET(::rpc::Response, _impl_.output_),
    PROTOBUF_FIELD_OFFSET(::rpc::Response, _impl_.iserror_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    {0, -1, -1, sizeof(::rpc::Request)},
    {8, -1, -1, sizeof(::rpc::Response)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::rpc::_Request_default_instance_._instance,
    &::rpc::_Response_default_instance_._instance,
};

const char descriptor_table_protodef_common_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
    "\n\014common.proto\022\003rpc\"(\n\007Request\022\016\n\006method"
    "\030\001 \001(\t\022\r\n\005input\030\002 \001(\014\";\n\010Response\022\016\n\006met"
    "hod\030\001 \001(\t\022\016\n\006output\030\002 \001(\014\022\017\n\007isError\030\003 \001"
    "(\010b\006proto3";
static ::_pbi::once_flag descriptor_table_common_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_common_2eproto = {
    false,
    false,
    130,
    descriptor_table_protodef_common_2eproto,
    "common.proto",
    &descriptor_table_common_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_common_2eproto::offsets,
    file_level_metadata_common_2eproto,
    file_level_enum_descriptors_common_2eproto,
    file_level_service_descriptors_common_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_common_2eproto_getter()
{
    return &descriptor_table_common_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_common_2eproto(
    &descriptor_table_common_2eproto);
namespace rpc
{

// ===================================================================

class Request::_Internal
{
  public:
};

Request::Request(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned)
    : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned)
{
    SharedCtor(arena, is_message_owned);
    // @@protoc_insertion_point(arena_constructor:rpc.Request)
}
Request::Request(const Request& from) : ::PROTOBUF_NAMESPACE_ID::Message()
{
    Request* const _this = this;
    (void)_this;
    new (&_impl_) Impl_{decltype(_impl_.method_){}, decltype(_impl_.input_){}, /*decltype(_impl_._cached_size_)*/ {}};

    _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
    _impl_.method_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.method_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
    if (!from._internal_method().empty())
    {
        _this->_impl_.method_.Set(from._internal_method(), _this->GetArenaForAllocation());
    }
    _impl_.input_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.input_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
    if (!from._internal_input().empty())
    {
        _this->_impl_.input_.Set(from._internal_input(), _this->GetArenaForAllocation());
    }
    // @@protoc_insertion_point(copy_constructor:rpc.Request)
}

inline void Request::SharedCtor(::_pb::Arena* arena, bool is_message_owned)
{
    (void)arena;
    (void)is_message_owned;
    new (&_impl_) Impl_{decltype(_impl_.method_){}, decltype(_impl_.input_){}, /*decltype(_impl_._cached_size_)*/ {}};
    _impl_.method_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.method_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.input_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.input_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Request::~Request()
{
    // @@protoc_insertion_point(destructor:rpc.Request)
    if (auto* arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>())
    {
        (void)arena;
        return;
    }
    SharedDtor();
}

inline void Request::SharedDtor()
{
    GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
    _impl_.method_.Destroy();
    _impl_.input_.Destroy();
}

void Request::SetCachedSize(int size) const { _impl_._cached_size_.Set(size); }

void Request::Clear()
{
    // @@protoc_insertion_point(message_clear_start:rpc.Request)
    uint32_t cached_has_bits = 0;
    // Prevent compiler warnings about cached_has_bits being unused
    (void)cached_has_bits;

    _impl_.method_.ClearToEmpty();
    _impl_.input_.ClearToEmpty();
    _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Request::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx)
{
#define CHK_(x)                                                                                                        \
    if (PROTOBUF_PREDICT_FALSE(!(x)))                                                                                  \
    goto failure
    while (!ctx->Done(&ptr))
    {
        uint32_t tag;
        ptr = ::_pbi::ReadTag(ptr, &tag);
        switch (tag >> 3)
        {
        // string method = 1;
        case 1:
            if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10))
            {
                auto str = _internal_mutable_method();
                ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
                CHK_(ptr);
                CHK_(::_pbi::VerifyUTF8(str, "rpc.Request.method"));
            }
            else
                goto handle_unusual;
            continue;
        // bytes input = 2;
        case 2:
            if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18))
            {
                auto str = _internal_mutable_input();
                ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
                CHK_(ptr);
            }
            else
                goto handle_unusual;
            continue;
        default:
            goto handle_unusual;
        } // switch
    handle_unusual:
        if ((tag == 0) || ((tag & 7) == 4))
        {
            CHK_(ptr);
            ctx->SetLastTag(tag);
            goto message_done;
        }
        ptr = UnknownFieldParse(
            tag, _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(), ptr, ctx);
        CHK_(ptr != nullptr);
    } // while
message_done:
    return ptr;
failure:
    ptr = nullptr;
    goto message_done;
#undef CHK_
}

uint8_t* Request::_InternalSerialize(uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const
{
    // @@protoc_insertion_point(serialize_to_array_start:rpc.Request)
    uint32_t cached_has_bits = 0;
    (void)cached_has_bits;

    // string method = 1;
    if (!this->_internal_method().empty())
    {
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
            this->_internal_method().data(), static_cast<int>(this->_internal_method().length()),
            ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "rpc.Request.method");
        target = stream->WriteStringMaybeAliased(1, this->_internal_method(), target);
    }

    // bytes input = 2;
    if (!this->_internal_input().empty())
    {
        target = stream->WriteBytesMaybeAliased(2, this->_internal_input(), target);
    }

    if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields()))
    {
        target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(
                ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance),
            target, stream);
    }
    // @@protoc_insertion_point(serialize_to_array_end:rpc.Request)
    return target;
}

size_t Request::ByteSizeLong() const
{
    // @@protoc_insertion_point(message_byte_size_start:rpc.Request)
    size_t total_size = 0;

    uint32_t cached_has_bits = 0;
    // Prevent compiler warnings about cached_has_bits being unused
    (void)cached_has_bits;

    // string method = 1;
    if (!this->_internal_method().empty())
    {
        total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(this->_internal_method());
    }

    // bytes input = 2;
    if (!this->_internal_input().empty())
    {
        total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(this->_internal_input());
    }

    return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Request::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck, Request::MergeImpl};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData* Request::GetClassData() const { return &_class_data_; }

void Request::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg)
{
    auto* const _this = static_cast<Request*>(&to_msg);
    auto& from = static_cast<const Request&>(from_msg);
    // @@protoc_insertion_point(class_specific_merge_from_start:rpc.Request)
    GOOGLE_DCHECK_NE(&from, _this);
    uint32_t cached_has_bits = 0;
    (void)cached_has_bits;

    if (!from._internal_method().empty())
    {
        _this->_internal_set_method(from._internal_method());
    }
    if (!from._internal_input().empty())
    {
        _this->_internal_set_input(from._internal_input());
    }
    _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Request::CopyFrom(const Request& from)
{
    // @@protoc_insertion_point(class_specific_copy_from_start:rpc.Request)
    if (&from == this)
        return;
    Clear();
    MergeFrom(from);
}

bool Request::IsInitialized() const { return true; }

void Request::InternalSwap(Request* other)
{
    using std::swap;
    auto* lhs_arena = GetArenaForAllocation();
    auto* rhs_arena = other->GetArenaForAllocation();
    _internal_metadata_.InternalSwap(&other->_internal_metadata_);
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(&_impl_.method_, lhs_arena, &other->_impl_.method_,
                                                                    rhs_arena);
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(&_impl_.input_, lhs_arena, &other->_impl_.input_,
                                                                    rhs_arena);
}

::PROTOBUF_NAMESPACE_ID::Metadata Request::GetMetadata() const
{
    return ::_pbi::AssignDescriptors(&descriptor_table_common_2eproto_getter, &descriptor_table_common_2eproto_once,
                                     file_level_metadata_common_2eproto[0]);
}

// ===================================================================

class Response::_Internal
{
  public:
};

Response::Response(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned)
    : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned)
{
    SharedCtor(arena, is_message_owned);
    // @@protoc_insertion_point(arena_constructor:rpc.Response)
}
Response::Response(const Response& from) : ::PROTOBUF_NAMESPACE_ID::Message()
{
    Response* const _this = this;
    (void)_this;
    new (&_impl_) Impl_{decltype(_impl_.method_){}, decltype(_impl_.output_){}, decltype(_impl_.iserror_){},
                        /*decltype(_impl_._cached_size_)*/ {}};

    _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
    _impl_.method_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.method_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
    if (!from._internal_method().empty())
    {
        _this->_impl_.method_.Set(from._internal_method(), _this->GetArenaForAllocation());
    }
    _impl_.output_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.output_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
    if (!from._internal_output().empty())
    {
        _this->_impl_.output_.Set(from._internal_output(), _this->GetArenaForAllocation());
    }
    _this->_impl_.iserror_ = from._impl_.iserror_;
    // @@protoc_insertion_point(copy_constructor:rpc.Response)
}

inline void Response::SharedCtor(::_pb::Arena* arena, bool is_message_owned)
{
    (void)arena;
    (void)is_message_owned;
    new (&_impl_) Impl_{decltype(_impl_.method_){}, decltype(_impl_.output_){}, decltype(_impl_.iserror_){false},
                        /*decltype(_impl_._cached_size_)*/ {}};
    _impl_.method_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.method_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.output_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.output_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Response::~Response()
{
    // @@protoc_insertion_point(destructor:rpc.Response)
    if (auto* arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>())
    {
        (void)arena;
        return;
    }
    SharedDtor();
}

inline void Response::SharedDtor()
{
    GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
    _impl_.method_.Destroy();
    _impl_.output_.Destroy();
}

void Response::SetCachedSize(int size) const { _impl_._cached_size_.Set(size); }

void Response::Clear()
{
    // @@protoc_insertion_point(message_clear_start:rpc.Response)
    uint32_t cached_has_bits = 0;
    // Prevent compiler warnings about cached_has_bits being unused
    (void)cached_has_bits;

    _impl_.method_.ClearToEmpty();
    _impl_.output_.ClearToEmpty();
    _impl_.iserror_ = false;
    _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Response::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx)
{
#define CHK_(x)                                                                                                        \
    if (PROTOBUF_PREDICT_FALSE(!(x)))                                                                                  \
    goto failure
    while (!ctx->Done(&ptr))
    {
        uint32_t tag;
        ptr = ::_pbi::ReadTag(ptr, &tag);
        switch (tag >> 3)
        {
        // string method = 1;
        case 1:
            if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10))
            {
                auto str = _internal_mutable_method();
                ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
                CHK_(ptr);
                CHK_(::_pbi::VerifyUTF8(str, "rpc.Response.method"));
            }
            else
                goto handle_unusual;
            continue;
        // bytes output = 2;
        case 2:
            if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18))
            {
                auto str = _internal_mutable_output();
                ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
                CHK_(ptr);
            }
            else
                goto handle_unusual;
            continue;
        // bool isError = 3;
        case 3:
            if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24))
            {
                _impl_.iserror_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
                CHK_(ptr);
            }
            else
                goto handle_unusual;
            continue;
        default:
            goto handle_unusual;
        } // switch
    handle_unusual:
        if ((tag == 0) || ((tag & 7) == 4))
        {
            CHK_(ptr);
            ctx->SetLastTag(tag);
            goto message_done;
        }
        ptr = UnknownFieldParse(
            tag, _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(), ptr, ctx);
        CHK_(ptr != nullptr);
    } // while
message_done:
    return ptr;
failure:
    ptr = nullptr;
    goto message_done;
#undef CHK_
}

uint8_t* Response::_InternalSerialize(uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const
{
    // @@protoc_insertion_point(serialize_to_array_start:rpc.Response)
    uint32_t cached_has_bits = 0;
    (void)cached_has_bits;

    // string method = 1;
    if (!this->_internal_method().empty())
    {
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
            this->_internal_method().data(), static_cast<int>(this->_internal_method().length()),
            ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "rpc.Response.method");
        target = stream->WriteStringMaybeAliased(1, this->_internal_method(), target);
    }

    // bytes output = 2;
    if (!this->_internal_output().empty())
    {
        target = stream->WriteBytesMaybeAliased(2, this->_internal_output(), target);
    }

    // bool isError = 3;
    if (this->_internal_iserror() != 0)
    {
        target = stream->EnsureSpace(target);
        target = ::_pbi::WireFormatLite::WriteBoolToArray(3, this->_internal_iserror(), target);
    }

    if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields()))
    {
        target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(
                ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance),
            target, stream);
    }
    // @@protoc_insertion_point(serialize_to_array_end:rpc.Response)
    return target;
}

size_t Response::ByteSizeLong() const
{
    // @@protoc_insertion_point(message_byte_size_start:rpc.Response)
    size_t total_size = 0;

    uint32_t cached_has_bits = 0;
    // Prevent compiler warnings about cached_has_bits being unused
    (void)cached_has_bits;

    // string method = 1;
    if (!this->_internal_method().empty())
    {
        total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(this->_internal_method());
    }

    // bytes output = 2;
    if (!this->_internal_output().empty())
    {
        total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(this->_internal_output());
    }

    // bool isError = 3;
    if (this->_internal_iserror() != 0)
    {
        total_size += 1 + 1;
    }

    return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Response::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck, Response::MergeImpl};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData* Response::GetClassData() const { return &_class_data_; }

void Response::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg)
{
    auto* const _this = static_cast<Response*>(&to_msg);
    auto& from = static_cast<const Response&>(from_msg);
    // @@protoc_insertion_point(class_specific_merge_from_start:rpc.Response)
    GOOGLE_DCHECK_NE(&from, _this);
    uint32_t cached_has_bits = 0;
    (void)cached_has_bits;

    if (!from._internal_method().empty())
    {
        _this->_internal_set_method(from._internal_method());
    }
    if (!from._internal_output().empty())
    {
        _this->_internal_set_output(from._internal_output());
    }
    if (from._internal_iserror() != 0)
    {
        _this->_internal_set_iserror(from._internal_iserror());
    }
    _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Response::CopyFrom(const Response& from)
{
    // @@protoc_insertion_point(class_specific_copy_from_start:rpc.Response)
    if (&from == this)
        return;
    Clear();
    MergeFrom(from);
}

bool Response::IsInitialized() const { return true; }

void Response::InternalSwap(Response* other)
{
    using std::swap;
    auto* lhs_arena = GetArenaForAllocation();
    auto* rhs_arena = other->GetArenaForAllocation();
    _internal_metadata_.InternalSwap(&other->_internal_metadata_);
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(&_impl_.method_, lhs_arena, &other->_impl_.method_,
                                                                    rhs_arena);
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(&_impl_.output_, lhs_arena, &other->_impl_.output_,
                                                                    rhs_arena);
    swap(_impl_.iserror_, other->_impl_.iserror_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Response::GetMetadata() const
{
    return ::_pbi::AssignDescriptors(&descriptor_table_common_2eproto_getter, &descriptor_table_common_2eproto_once,
                                     file_level_metadata_common_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
} // namespace rpc
PROTOBUF_NAMESPACE_OPEN
template <> PROTOBUF_NOINLINE ::rpc::Request* Arena::CreateMaybeMessage<::rpc::Request>(Arena* arena)
{
    return Arena::CreateMessageInternal<::rpc::Request>(arena);
}
template <> PROTOBUF_NOINLINE ::rpc::Response* Arena::CreateMaybeMessage<::rpc::Response>(Arena* arena)
{
    return Arena::CreateMessageInternal<::rpc::Response>(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
